# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-19 04:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture_code', models.CharField(default='0000000', max_length=120)),
                ('day', models.CharField(choices=[('月', '月曜日'), ('火', '火曜日'), ('水', '水曜日'), ('木', '木曜日'), ('金', '金曜日')], max_length=120, null=True)),
                ('time', models.CharField(choices=[('1', '1限目'), ('2', '2限目'), ('3', '3限目'), ('4', '4限目'), ('5', '5限目')], max_length=120, null=True)),
                ('lecture_type', models.CharField(choices=[('基礎セミナー', '基礎セミナー'), ('言語文化Ⅰ', '言語文化Ⅰ'), ('言語文化Ⅱ', '言語文化Ⅱ'), ('言語文化Ⅲ', '言語文化Ⅲ'), ('健康・スポーツ科学', '健康・スポーツ科学'), ('文系基礎科目', '文系基礎科目'), ('理系基礎科目（文系）', '理系基礎科目（文系）'), ('理系基礎科目（理系）', '理系基礎科目（理系）'), ('文系教養科目', '文系教養科目'), ('理系教養科目', '理系教養科目'), ('全学教養科目', '全学教養科目'), ('開放科目', '開放科目'), ('文学部専門', '文学部専門'), ('教育学部専門', '教育学部専門'), ('法学部専門', '法学部専門'), ('経済学部専門', '経済学部専門'), ('情報学部専門', '情報学部専門/情報文化学部専門'), ('理学部専門', '理学部専門'), ('医学部専門', '医学部専門'), ('工学部専門', '工学部専門'), ('農学部専門', '農学部専門')], max_length=120, null=True)),
                ('title', models.CharField(max_length=120)),
                ('professor_name', models.CharField(max_length=120)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('syllabus', models.CharField(blank=True, max_length=120, null=True)),
                ('target', models.CharField(max_length=120, null=True)),
                ('description', models.TextField(null=True)),
                ('year', models.CharField(max_length=120)),
                ('credit', models.DecimalField(decimal_places=2, max_digits=3)),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='date published')),
            ],
        ),
    ]
