# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-19 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0002_auto_20180219_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='credit',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
    ]
