# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-20 19:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0003_auto_20180219_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='day',
            field=models.CharField(choices=[('1', '月曜日'), ('2', '火曜日'), ('3', '水曜日'), ('4', '木曜日'), ('5', '金曜日')], max_length=120, null=True),
        ),
    ]
