# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-28 02:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0005_lecture_popular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='credit',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2),
        ),
    ]
