# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-28 05:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0006_auto_20180228_0229'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lecture',
            options={'ordering': ['-created_at']},
        ),
    ]
