# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-19 22:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lecture', '0003_auto_20180219_1658'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='No Title', max_length=120)),
                ('comment', models.TextField(blank=True, null=True)),
                ('rate_pass', models.CharField(choices=[('100', 'S：100'), ('90', 'A：90'), ('80', 'B：80'), ('70', 'C：70'), ('60', 'F：60')], default='80', max_length=20)),
                ('rate_professor', models.CharField(choices=[('100', 'S：100'), ('90', 'A：90'), ('80', 'B：80'), ('70', 'C：70'), ('60', 'F：60')], default='80', max_length=20)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='lecture.Lecture')),
            ],
        ),
    ]
