# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-19 22:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('grade', '0001_initial'),
        ('student', '0002_auto_20180219_2259'),
        ('lecture', '0003_auto_20180219_1658'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='No Title', max_length=30)),
                ('fri1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fri1', to='lecture.Lecture')),
                ('fri2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fri2', to='lecture.Lecture')),
                ('fri3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fri3', to='lecture.Lecture')),
                ('fri4', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fri4', to='lecture.Lecture')),
                ('fri5', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fri5', to='lecture.Lecture')),
                ('grade', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timetable', to='grade.Grade')),
                ('mon1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mon1', to='lecture.Lecture')),
                ('mon2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mon2', to='lecture.Lecture')),
                ('mon3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mon3', to='lecture.Lecture')),
                ('mon4', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mon4', to='lecture.Lecture')),
                ('mon5', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mon5', to='lecture.Lecture')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable', to='student.Student')),
                ('thu1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thu1', to='lecture.Lecture')),
                ('thu2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thu2', to='lecture.Lecture')),
                ('thu3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thu3', to='lecture.Lecture')),
                ('thu4', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thu4', to='lecture.Lecture')),
                ('thu5', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thu5', to='lecture.Lecture')),
                ('tue1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tue1', to='lecture.Lecture')),
                ('tue2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tue2', to='lecture.Lecture')),
                ('tue3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tue3', to='lecture.Lecture')),
                ('tue4', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tue4', to='lecture.Lecture')),
                ('tue5', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tue5', to='lecture.Lecture')),
                ('wed1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wed1', to='lecture.Lecture')),
                ('wed2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wed2', to='lecture.Lecture')),
                ('wed3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wed3', to='lecture.Lecture')),
                ('wed4', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wed4', to='lecture.Lecture')),
                ('wed5', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wed5', to='lecture.Lecture')),
            ],
        ),
    ]
