# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-20 19:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_auto_20180220_0339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='grade',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timetable', to='grade.Grade'),
        ),
    ]
