# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-19 05:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('active', models.BooleanField(default=True)),
                ('department', models.CharField(choices=[('文学部', '文学部'), ('教育学部', '教育学部'), ('法学部', '法学部'), ('経済学部', '経済学部'), ('情報学部', '情報学部'), ('理学部', '理学部'), ('医学部', '医学部'), ('工学部', '工学部'), ('農学部', '農学部')], max_length=30, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
