# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-19 22:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grade', '0001_initial'),
        ('lecture', '0003_auto_20180219_1658'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='favorite_lecture',
            field=models.ManyToManyField(related_name='favorite_student', to='lecture.Lecture'),
        ),
        migrations.AddField(
            model_name='student',
            name='grade',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student', to='grade.Grade'),
        ),
    ]
