# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-20 19:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20180220_0339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.CharField(choices=[('文学部', '文学部'), ('教育学部', '教育学部'), ('法学部', '法学部'), ('経済学部', '経済学部'), ('情報学部', '情報学部/情報文化学部'), ('理学部', '理学部'), ('医学部', '医学部'), ('工学部', '工学部'), ('農学部', '農学部')], max_length=30, null=True),
        ),
    ]
